cronjobs:
  dev-scenario:
    scriptPath: test.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: dev-scenario
    image: ghcr.io/dbildungsplattform/spsh-k6-loadtest:latest
    environment: spsh.loadtest.dbildungscloud.dev
  