branch: "main"
imageTag: latest #default latest, release oder main ?
port: 5656
schedule: 0 8 * * *
pattern: "dummy_pattern"
config: "dummy_config"
max_vus: "10"

cronjobs:
  current:
    serviceName: spsh-1371
    spsh_base: "https://spsh-1371.dev.spsh.dbildungsplattform.de"
  dev-scenario:
    serviceName: dev-scenario
    spsh_base: "https://main.dev.spsh.dbildungsplattform.de"
    kc_base: "kc_base"
  staging-scenario:
    serviceName: staging-scenario
    spsh_base: "https://spsh.staging.spsh.dbildungsplattform.de"
    kc_base: "https://keycloak.staging.spsh.dbildungsplattform.de"
  prod-scenario:
    serviceName: prod-scenario
    spsh_base: "https://spsh.dbildungsplattform.de"
