branch: "main"

cronjobs:
  dev-scenario:
    scriptPath: 1_goto-sp-oidc.ts # 01, 02, 03 Files
    schedule: 0 8 * * *
    port: 5656
    serviceName: dev-scenario
    imageTag: 
      ${{ if eq(git.branch, 'main') }}: latest
      ${{ else }}: ${{ git.branch }}
    environment: main.dev.spsh.dbildungsplattform.de
    # jobsParallelism: not used yet but available? test it
  # staging-scenario:
  #   scriptPath: 
  #   schedule: 0 8 * * *
  #   port: 5656
  #   serviceName: staging-scenario
  #   image: ghcr.io/dbildungsplattform/schulportal-load-tests:latest
  #   environment: spsh.staging.dbildungsplattform.de
  # prod-scenario:
  #   scriptPath: 
  #   schedule: 0 8 * * *
  #   port: 5656
  #   serviceName: prod-scenario
  #   image: ghcr.io/dbildungsplattform/schulportal-load-tests:latest
  #   environment: spsh.dbildungsplattform.de
