{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-spsh-{{ $job_name }}
  namespace: spsh
spec:
  schedule: {{ $job_options.schedule }}
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      template:
        metadata:
          labels:
            test: loadtest-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          containers:
          - name: {{ $job_name }}
            image: {{ $job_options.image }}
            securityContext:
              allowPrivilegeEscalation: false
            imagePullPolicy: Always
            env:
              - name: OPTIONS_FILE_PATH
                value: testoption.json
              - name: BRANCH
                value: main
            args:
              ['k6','run', '-u', '0',
                         './loadtest/tests/{{ $job_options.scriptPath }}',
                         '--tag','NAME={{ $job_options.serviceName }}',
                         #'--out', 'experimental-prometheus-rw',
                         '-e', 'ENVIRONMENT={{ $job_options.environment }}']
            #volumeMounts:
            #- name: secret-volume
            #  mountPath: /secrets
            #  readOnly: true
            ports:
            - containerPort: {{ $job_options.port }}
              name: loadtest-pod
          #volumes:
          #- name: secret-volume
          #  secret:
          #    secretName: spsh-loadtest-secret
          restartPolicy: Never
---
{{- end}}