{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-spsh-{{ $job_name }}
  namespace: spsh
spec:
  schedule: {{ $.Values.schedule }}
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      backoffLimit: 0
      template:
        metadata:
          labels:
            test: loadtest-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          automountServiceAccountToken: false
          containers:
          - name: {{ $job_name }}
            image: ghcr.io/dbildungsplattform/schulportal-load-tests:{{ $.Values.imageTag }}
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
            env:
              - name: BRANCH
                value: {{ $.Values.branch }}
              - name: SPSH_BASE
                value: {{ $job_options.spsh_base }}
              - name: CONFIG
                value: {{ $.Values.config }}
              - name: KC_BASE
                value: {{ $job_options.kc_base }}
              - name: PATTERN
                value: {{ $.Values.pattern }}
              - name: MAX_VUS
                value: {{ $.Values.max_vus | quote }}
            command: ["sh", "-c", 
                        "git clone https://github.com/dBildungsplattform/schulportal-load-tests &&
                        cd schulportal-load-tests && 
                        git checkout {{ $.Values.branch }} && 
                        cp /data/json/users.json /home/k6/schulportal-load-tests/loadtest/data/users.json &&
                        chmod +x run.sh &&
                        ./run.sh $SPSH_BASE $CONFIG $PATTERN $MAX_VUS $KC_BASE "]
            volumeMounts:
              - name: secret-volume
                mountPath: /secrets
                readOnly: true
              - name: secret-volume-json
                mountPath: /data/json
                readOnly: true
            ports:
            - containerPort: {{ $.Values.port }}
              name: loadtest-pod
          volumes:
          - name: secret-volume
            secret:
              secretName: spsh-loadtest-secret
          - name: secret-volume-json
            secret:
              secretName: spsh-loadtest-secret-json
          restartPolicy: Never
---
{{- end}}