{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-spsh-{{ $job_name }}
  namespace: spsh
spec:
  schedule: {{ $job_options.schedule }}
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      # is defined in here but not activaly used? 
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      template:
        metadata:
          labels:
            test: loadtest-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          automountServiceAccountToken: false
          containers:
          - name: {{ $job_name }}
            image: ghcr.io/dbildungsplattform/schulportal-load-test:{{ $job_options.iamgeTag }}
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
            env:
              - name: OPTIONS_FILE_PATH
                value: testoption.json
              - name: BRANCH
                value: main
              - name: SPSH_BASE
                value: main.dev.spsh.dbildungsplattform.de
              - name: CONFIG
                value: stress
            command: ["sh", "-c", "git clone https://github.com/dBildungsplattform/schulportal-load-tests && cd schulportal-load-tests && git checkout DBP-1012-setup-loadtest-env && k6 '$@'"]
            args: [ 'k6','run', '-u', '0',
                         './loadtest/usecases/{{ $job_options.scriptPath }}',
                         '--compatibility-mode=experimental_enhanced',
                  ]
            volumeMounts:
              - name: secret-volume
                mountPath: /secrets
                readOnly: true
              - name: secret-volume-json
                mountPath: /data/json
                readOnly: true
            ports:
            - containerPort: {{ $job_options.port }}
              name: loadtest-pod
          volumes:
          - name: secret-volume
            secret:
              secretName: spsh-loadtest-secret
          volumes:
          - name: secret-volume-json
            secret:
              secretName: spsh-loadtest-secret-json
          restartPolicy: Never
---
{{- end}}