---
name: Install and Run SPSH Loadtest Action 

on: 
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: main
    secrets:
      KUBECONFIG:
        required: true

permissions:
  contents: read

concurrency:
  group: schulportal-load-tests-rollout-run
  cancel-in-progress: true

jobs:
  rollout:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: 'dBildungsplattform/schulportal-load-tests'
          # change this ref to a branch to test changes
          # ref: "${{ inputs.branch }}"
          ref: "DBP-1012-setup-loadtest-env"

      - name: Install kubectl and Helm
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f #v4.0.0

      - name: Set kubeconfig
        run: |
          mkdir /home/runner/.kube/
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
          chmod 600 /home/runner/.kube/config

      - name: Rollout schulportal-load-tests Helm Chart 
        run: |
            helm upgrade --install \
            schulportal-load-tests \
            ./charts/schulportal-load-tests \
            --namespace spsh \
            --kubeconfig /home/runner/.kube/config \
            --wait
