---
name: Install SPSH Loadtest Action 

on: 
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: main
      pattern:
        type: string
        required: false
        default: "login"
      config:
        type: string 
        required: false
        default: "debug"
      scenario:
        type: string
        required: true
        default: dev-scenario
      execute:
        type: boolean
        required: true
        default: true

    secrets:
      KUBECONFIG:
        required: true

permissions:
  contents: read

concurrency:
  group: schulportal-load-tests-rollout-run
  cancel-in-progress: true

jobs:
  branch_meta:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch_meta.outputs.branch }}
      ticket: ${{ steps.extract_branch_ticket.outputs.ticket }}
    steps:
      - name: Extract branch meta
        shell: bash
        id: extract_branch_meta
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
      - name: Extract project-ticketnumber from branch
        id: extract_branch_ticket
        run: |
          if ${{ github.ref_name == 'main' }}; then
            echo "ticket=main" >> $GITHUB_OUTPUT
          else
            regex='^([[:alpha:]]+?-[[:digit:]]+)'
            [[ ${{ steps.extract_branch_meta.outputs.branch }} =~ $regex ]]
            echo "ticket=$(echo ${BASH_REMATCH[1]} | tr [A-Z] [a-z])" >> $GITHUB_OUTPUT
          fi

  rollout:
    runs-on: 'ubuntu-latest'
    needs: branch_meta
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: 'dBildungsplattform/schulportal-load-tests'
          # change this ref to a branch to test changes
          ref: "${{ inputs.branch }}"

      - name: Install kubectl and Helm
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f #v4.0.0

      - name: Set kubeconfig
        run: |
          mkdir /home/runner/.kube/
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
          chmod 600 /home/runner/.kube/config

      - name: Rollout schulportal-load-tests Helm Chart 
        run: |
            helm upgrade --install \
            schulportal-load-tests \
            ./charts/schulportal-load-tests \
            --namespace spsh \
            --kubeconfig /home/runner/.kube/config \
            --set branch="${{ inputs.branch }}" \
            --set pattern="${{ inputs.pattern }}" \
            --set config="${{ inputs.config }}" \
            ${{ inputs.branch != 'main' && format('--set imageTag="{0}"', needs.branch_meta.outputs.ticket ) || '--set imageTag="latest"' }} \
            --wait

      - name: Trigger Loadtest CronJob
        if: ${{ inputs.execute }}
        run: |
          kubectl create job --from=cronjob/loadtest-spsh-${{inputs.scenario}} ${{ inputs.scenario}}-${{inputs.branch}}$(date +%d.%m.%Y-%H:%M:%S) -n spsh
        # kubectl create job --from=cronjob/<cronjob-name> <job-name> -n <namespace-name>
