name: 'Publish image to GHCR on push to branch'

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: spsh-loadtest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@5.0.0
    with:
      image_name: "spsh-k6-loadtest"
      run_trivy_scan: true
      image_tag_generation: "ticket_from_branch"
      add_latest_tag: false
      container_registry: "ghcr.io"
