name: 'Publish image to GHCR and Helm chart to GH pages on tag'

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: spsh-loadtest-main
  cancel-in-progress: true

jobs:
  publish_docker:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@5.0.0
    with:
      image_name: "spsh-k6-loadtest"
      run_trivy_scan: true
      image_tag_generation: "version_git_tag"
      add_latest_tag: true
      container_registry: "ghcr.io"
  publish_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@5.0.0
    secrets: inherit
    with:
      chart_name: spsh-k6-loadtest
      helm_chart_version_generation: specified
      image_tag_generation: specified
      helm_chart_version: ${{ github.ref_name }}
      image_tag: ${{ github.ref_name }}
