name: "Publish image to GHCR and Helm chart to GH pages on tag"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: schulportal-load-tests-main
  cancel-in-progress: true

jobs:
  publish_docker:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@5.0.0
    with:
      image_name: "schulportal-load-tests"
      run_trivy_scan: true
      image_tag_generation: "version_git_tag"
      add_latest_tag: true
      container_registry: "ghcr.io"
