---
name: Trigger Loadtest 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to take tests and helm/cron setup  from'
        required: false
        type: string
        default: main
      pattern:
        description: 'sets PATTERN env var used as k6 input'
        required: false
        type: string
        default: "login"
      config:
        description: 'sets CONFIG env var used as k6 input'
        required: false
        type: string
        default: "debug"
      scenario-list:
        description: 'name list of test scenarios defined in values.yaml (scenario1,scenario2,...)'
        type: string
        required: true
        default: dev-scenario
      execute:
        description: "execute cronjob scenario after install"
        type: boolean
        required: true
        default: false

jobs:
  install_loadtest:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: ./.github/workflows/install-and-run-spsh-loadtest.yml
    with:
      branch: ${{ inputs.branch }} 
      pattern: ${{ inputs.pattern }} 
      config: ${{ inputs.config }} 
      scenario-list: ${{ inputs.scenario-list }}
      execute: ${{ inputs.execute }}
    secrets: 
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

    