---
name: Trigger Loadtest

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to take tests and helm/cron setup  from'
        required: false
        default: main

jobs:
  run_loadtest:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: ./.github/workflows/install-spsh-loadtest.yml
    with:
      branch: ${{ inputs.branch }} 
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}