---
name: Trigger Loadtest

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to take tests and helm/cron setup  from'
        required: false
        default: main
      pattern:
        description: 'sets PATTERN env var used as k6 input'
        required: false
        default: "default_pattern"
      config:
        description: 'sets CONFIG env var used as k6 input'
        required: false
        default: "default_config"

jobs:
  run_loadtest:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: ./.github/workflows/install-spsh-loadtest.yml
    with:
      branch: ${{ inputs.branch }} 
      pattern: ${{ inputs.pattern }} 
      config: ${{ inputs.config }} 
    secrets: 
      KUBECONFIG: ${{ secrets.KUBECONFIG }}