---
name: Trigger Loadtest 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to take tests and helm/cron setup  from'
        required: false
        type: string
        default: DBP-1012-setup-loadtest-env
        # default: main
      pattern:
        description: 'sets PATTERN env var used as k6 input'
        required: false
        type: string
        default: "login"
      config:
        description: 'sets CONFIG env var used as k6 input'
        required: false
        type: string
        default: "debug"
      scenario:
        description: 'name of test scenario defined in values.yaml'
        type: string
        required: true
        default: dev-scenario

jobs:
  install_loadtest:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: ./.github/workflows/install-spsh-loadtest.yml
    with:
      branch: ${{ inputs.branch }} 
      pattern: ${{ inputs.pattern }} 
      config: ${{ inputs.config }} 
    secrets: 
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

  run_loadtest:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Loadtest CronJob
        run: |
          kubectl create job --from=cronjob/loadtest-spsh-${{inputs.scenario}} ${{ inputs.scenario}}-${{inputs.branch}}$(date +%d.%m.%Y-%H:%M:%S) -n spsh
        # kubectl create job --from=cronjob/<cronjob-name> <job-name> -n <namespace-name>
    