---
name: Trigger Loadtest

on:
  workflow_dispatch:
    inputs:
      branch_code:
        description: "Branch to take test code and helm/cron setup from"
        required: false
        type: string
        default: SPSH-1378
      branch_img:
        description: "Branch to take Dockerfile/img from"
        required: false
        type: string
        default: main
      pattern:
        description: "sets PATTERN env var used as k6 input"
        required: false
        type: string
        default: "login"
      config:
        description: "sets CONFIG env var used as k6 input"
        required: false
        type: string
        default: "plateau"
      max_vus:
        description: "sets the maximum number of virtual users"
        required: false
        type: string
        default: "10"
      scenario:
        description: "name of test scenario defined in values.yaml"
        type: string
        required: true
        default: current
      execute:
        description: "execute cronjob scenario after install"
        type: boolean
        required: true
        default: true

jobs:
  install_loadtest:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: ./.github/workflows/install-and-run-spsh-loadtest.yml
    with:
      branch_code: ${{ inputs.branch_code }}
      branch_img: ${{ inputs.branch_img }}
      pattern: ${{ inputs.pattern }}
      config: ${{ inputs.config }}
      max_vus: ${{ inputs.max_vus }}
      scenario: ${{ inputs.scenario }}
      execute: ${{ inputs.execute }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
